# config/services.yaml

parameters:
    picture_parameter: '%kernel.project_dir%/public/image/product'

services:
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique des services (commandes, event subscribers...)

    # Déclaration explicite pour la session
    Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'

    # Enregistre tous les services de src/ sauf les dossiers exclus
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
